Traceback (most recent call last):
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/estim_seg3d.py", line 104, in <module>
    main()
  File "/well/win-fmrib-analysis/users/gqu790/moval/moval_scripts/estim_seg3d.py", line 94, in main
    moval_model.fit(logits, gt)
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/moval/integrations/sklearn/moval.py", line 246, in fit
    self.fitted_perf = self.get_case_perf(model, self.metric, logits, gt)
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/moval/integrations/sklearn/moval.py", line 349, in get_case_perf
    estim_perf_case = model.estimate_precision(probability[n_case:n_case + 1], gt_guide = gt_guide[n_case:n_case + 1])
  File "/well/win-fmrib-analysis/users/gqu790/conda/skylake/envs/moval/lib/python3.8/site-packages/moval/models/model.py", line 296, in estimate_precision
    raise ValueError(f"estimation algorithm '{self.estim_algorithm}' does not support the estimation of precision (because FP is always 0)")
ValueError: estimation algorithm 'ts-atc-model' does not support the estimation of precision (because FP is always 0)
